apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helper.fullname" . }}-configmap
  labels:
  {{- include "helper.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configmap | nindent 2 }}
